### ISSUE TITLE
`mvn install` leads to Error 504: Gateway Time-out

### ISSUE THREAD

**Issue by frankniujc** [CogComp/cogcomp-nlp#726]
Hello, I encountered the following error when trying to build the pipeline.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:11 h
[INFO] Finished at: 2019-10-10T17:06:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project illinois-nlp-pipeline: Could not resolve dependencies for project edu.illinois.cs.cogcomp:illinois-nlp-pipeline:jar:4.0.15: Failed to collect dependencies at edu.illinois.cs.cogcomp:illinois-core-utilities:jar:4.0.15: Failed to read artifact descriptor for edu.illinois.cs.cogcomp:illinois-core-utilities:jar:4.0.15: Could not transfer artifact edu.illinois.cs.cogcomp:illinois-core-utilities:pom:4.0.15 from/to Atilika Open Source repository (http://www.atilika.org/nexus/content/repositories/atilika): Failed to transfer file: http://www.atilika.org/nexus/content/repositories/atilika/edu/illinois/cs/cogcomp/illinois-core-utilities/4.0.15/illinois-core-utilities-4.0.15.pom. Return code is: 504 , ReasonPhrase:Gateway Time-out. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/
```

**Comment by Slash0BZ** [comment]
Should be fixed now, sorry about the problem. Please make sure you are using JDK8, there are known issues with other versions. Thanks.

**Comment by frankniujc** [comment]
Hello @Slash0BZ,

Thanks for the response! However the

**Comment by frankniujc** [comment]
Hello @Slash0BZ,

Thanks for the response! However, it seems that the issue is still there.
I am using JDK8 and here are my maven info
```
$ mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_222, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-65-generic", arch: "amd64", family: "unix"
```

**Comment by Slash0BZ** [comment]
Hi, sorry I wasn't clear: you need to re-download the current version of the code. It was something with the code instead of the maven repository. Please let me know if you can try that. Thanks.

**Comment by frankniujc** [comment]
Thank you so much. Right now it can be built successfully.
